version: '3.3'

services:
  postgres:
    image: postgres:11.2
    container_name: easybuy-database
    restart: always
    environment:
      - TZ=UTC
      - PGTZ=UTC
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=easybuy
    ports:
      - 5432:5432
    volumes:
      - easybuy-db-data:/var/lib/postgresql/data
    networks:
      - easybuy-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 20s
      timeout: 5s
      retries: 5

  easybuy-backend:
    container_name: easybuy-backend
    build:
      context: .
      dockerfile: Dockerfile
    image: easybuy-backend:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - easybuy-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

volumes:
  easybuy-db-data:
    driver: local

networks:
  easybuy-network:
    driver: bridge